// server.js
import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import OpenAI from "openai";

const app = express();
const port = 3000;

// ---------------- LM Studio as OpenAI-compatible server ----------------
const client = new OpenAI({
  baseURL: "http://127.0.0.1:1234/v1", // LM Studio OpenAI server，一定要有 /v1
  apiKey: "not-needed",                // LM Studio 唔 check，但 SDK 需要個值
});

// 取得 __dirname（因為用 ES module）
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 靜態檔案（前端）
app.use(express.static(path.join(__dirname, "public")));
app.use(express.json());

// ---------------- Tools / Functions 定義 ----------------

// 1) 真正執行嘅 JS function：攞系統時間
function getCurrentTime() {
  const now = new Date();
  return {
    iso: now.toISOString(),
    locale: now.toLocaleString(), // 根據 server 所在地
  };
}

// 2) 🆕 JS function：驗證由 AI 填入嘅 plan（AI 生成內容，呢度只係做 JSON 潔淨 / 限制）
//    args.plan 應該係一個 array，每個 item 至少有 time / activity
function createWorkoutPlanTool(args = {}) {
  const rawPlan = Array.isArray(args.plan) ? args.plan : [];
  const plan = [];

  for (const item of rawPlan) {
    if (!item || typeof item !== "object") continue;

    let { time, activity, durationMinutes } = item;

    if (typeof time !== "string" || typeof activity !== "string") {
      continue; // 唔合規就 skip
    }

    // 做少少清理，避免太長內容
    time = time.slice(0, 100);
    activity = activity.slice(0, 300);

    const cleaned = { time, activity };

    if (
      typeof durationMinutes === "number" &&
      durationMinutes > 0 &&
      durationMinutes < 300
    ) {
      cleaned.durationMinutes = durationMinutes;
    }

    plan.push(cleaned);
  }

  // 如果 AI 生成完全唔合規，就回空陣列
  if (plan.length === 0) {
    return { plan: [] };
  }

  // 防止太長（避免前端爆 UI）
  if (plan.length > 40) {
    plan.length = 40;
  }

  return { plan };
}


// Tool schema（比 LM Studio / model 睇）
// 現在有兩個 tools：getCurrentTime + createWorkoutPlan
const tools = [
  {
    type: "function",
    function: {
      name: "getCurrentTime",
      description: "Get the current local time of the server.",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "createWorkoutPlan",
      description:
        "Create a full workout schedule. The model must generate the complete plan inside the 'plan' array before calling this tool.",
      parameters: {
        type: "object",
        properties: {
          plan: {
            type: "array",
            description:
              "The full workout schedule generated by the model. Each item represents one step in the schedule.",
            items: {
              type: "object",
              properties: {
                time: {
                  type: "string",
                  description: "Time label, e.g. '8:00 AM' or 'Day 1 - Morning'.",
                },
                activity: {
                  type: "string",
                  description: "Workout description or instructions.",
                },
                durationMinutes: {
                  type: "integer",
                  description:
                    "Optional estimated duration in minutes for this activity.",
                },
              },
              required: ["time", "activity"],
              additionalProperties: false,
            },
          },
        },
        required: ["plan"],
        additionalProperties: false,
      },
    },
  },
];

// ---------------- Chat endpoint ----------------

app.post("/api/chat", async (req, res) => {
  try {
    const userMessage = req.body.message || "";
    const roomName = req.body.roomName || "General Health";

    const baseMessages = [
      {
        role: "system",
        content:
          "You are a friendly Cantonese-speaking health assistant. " +
          "Reply mainly in Cantonese, but keep health/fitness terms in English when appropriate. " +
          //"You MUST always remind users that you are not a doctor and they should consult professionals for medical concerns. " +
          "If the user asks about the current time / now / 幾點, you SHOULD use the getCurrentTime tool. " +
          "If the user asks for a workout schedule, exercise plan, gym routine, 或者『幫我整運動時間表』，" +
          "YOU MUST first design a complete workout timetable in your mind, then call the createWorkoutPlan tool " +
          "by filling the 'plan' array with JSON objects: { time, activity, durationMinutes? }. " +
          "Make sure to include any specific constraints the user asked for, such as '12:00 PM 30-min yoga'. " +
          `The current chat room name is: "${roomName}", use it only as soft context about their goal.`,
      },
      { role: "user", content: userMessage },
    ];


    // 1️⃣ 第一次 call LM Studio：等佢決定用唔用 tools
    const first = await client.chat.completions.create({
      model: "nousresearch-hermes-2-pro-llama-3-8b-molecule16-i1",
      messages: baseMessages,
      tools,
      tool_choice: "auto",
    });

    console.log(
      "First response from LM Studio:",
      JSON.stringify(first, null, 2),
    );

    if (!first.choices || first.choices.length === 0) {
      return res.status(500).json({
        type: "text",
        message: "對唔住，AI 冇正常回應。",
        scheduleData: null,
        dietData: null,
        usedTool: false,
        raw: first,
      });
    }

    const firstMsg = first.choices[0].message;
    const toolCalls = firstMsg.tool_calls;

    // 如果冇用任何 tool → 普通文字回答
    if (!toolCalls || toolCalls.length === 0) {
      return res.json({
        type: "text",
        message: firstMsg.content,
        scheduleData: null,
        dietData: null,
        usedTool: false,
      });
    }

    // 情況 B：用咗 tools，我哋逐個執行，並且收集 scheduleData（俾前端畫卡）
    const toolMessages = [];
    let scheduleData = null; // 用來回俾前端嘅 workout schedule（如果有）

    for (const call of toolCalls) {
      const toolName = call.function.name;
      let toolResult = null;

      // 將 arguments 由 JSON string 變成 JS object
      let args = {};
      try {
        args = call.function.arguments
          ? JSON.parse(call.function.arguments)
          : {};
      } catch (e) {
        console.warn("Failed to parse tool arguments:", e);
      }

      if (toolName === "getCurrentTime") {
        toolResult = getCurrentTime();
      } else if (toolName === "createWorkoutPlan") {
        // args.plan 由 AI 生成，呢度做 validation＋清理
        const { plan } = createWorkoutPlanTool(args);
        toolResult = { plan };
        scheduleData = plan; // scheduleData 俾前端當作 schedule card 用
      } else {
        toolResult = { error: `Unknown tool: ${toolName}` };
      }

      toolMessages.push({
        role: "tool",
        tool_call_id: call.id,
        name: toolName,
        content: JSON.stringify(toolResult),
      });
    }

    // 2️⃣ 第二次 call LM Studio：畀 tool 結果，叫佢用自然語言講返
    const second = await client.chat.completions.create({
      model: "nousresearch-hermes-2-pro-llama-3-8b-molecule16-i1",
      messages: [...baseMessages, firstMsg, ...toolMessages],
    });

    console.log(
      "Second response from LM Studio:",
      JSON.stringify(second, null, 2),
    );

    if (!second.choices || second.choices.length === 0) {
      return res.status(500).json({
        type: "text",
        message: "對唔住，AI 喺處理工具結果時出現咗問題。",
        scheduleData,
        dietData: null,
        usedTool: true,
        raw: second,
      });
    }

    const finalMsg = second.choices[0].message;

    // 如果有 scheduleData → 當作 schedule message，俾前端畫 workout card
    const responseType = scheduleData ? "schedule" : "text";

    res.json({
      type: responseType,        // "schedule" 或 "text"
      message: finalMsg.content, // AI 用自然語言講返 result
      scheduleData: scheduleData,
      dietData: null,            // 之後你可以加 createDietPlan 時用
      usedTool: true,
    });
  } catch (err) {
    console.error("Error in /api/chat:", err);
    res.status(500).json({
      type: "text",
      message: "Server error，請稍後再試。",
      scheduleData: null,
      dietData: null,
      usedTool: false,
      detail: String(err),
    });
  }
});

// 啟動 server
app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
