// server.js
import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import OpenAI from "openai";

const app = express();
const port = 3000;

// ---------------- LM Studio as OpenAI-compatible server ----------------
const client = new OpenAI({
  baseURL: "http://127.0.0.1:1234/v1", // LM Studio OpenAI server，一定要有 /v1
  apiKey: "not-needed",                // LM Studio 唔 check，但 SDK 需要個值
});

// 取得 __dirname（因為用 ES module）
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 靜態檔案（前端）
app.use(express.static(path.join(__dirname, "public")));
app.use(express.json());

// ---------------- Tools / Functions 定義 ----------------

// 1) 攞系統時間
function getCurrentTime() {
  const now = new Date();
  return {
    iso: now.toISOString(),
    locale: now.toLocaleString(), // 根據 server 所在地
  };
}

// 2) Workout Plan Validator
//    AI 會喺 arguments.plan 入面塞好整份 timetable，呢度淨係做 JSON validation / 清理
function createWorkoutPlanTool(args = {}) {
  const rawPlan = Array.isArray(args.plan) ? args.plan : [];
  const plan = [];

  for (const item of rawPlan) {
    if (!item || typeof item !== "object") continue;

    let { time, activity, durationMinutes } = item;

    if (typeof time !== "string" || typeof activity !== "string") {
      continue; // 唔合規就 skip
    }

    // 簡單防止太長文字
    time = time.slice(0, 100);
    activity = activity.slice(0, 300);

    const cleaned = { time, activity };

    if (
      typeof durationMinutes === "number" &&
      durationMinutes > 0 &&
      durationMinutes < 300
    ) {
      cleaned.durationMinutes = durationMinutes;
    }

    plan.push(cleaned);
  }

  if (plan.length === 0) {
    return { plan: [] };
  }

  // 防止 AI 生太多行搞到 UI 爆
  if (plan.length > 40) {
    plan.length = 40;
  }

  return { plan };
}

// 3) 🆕 Diet Plan Validator
//    同樣地，AI 會喺 arguments.plan 入面塞好完整 diet timetable
//    每一行至少要有 time + meal；caloriesEstimate 係 optional
function createDietPlanTool(args = {}) {
  const rawPlan = Array.isArray(args.plan) ? args.plan : [];
  const plan = [];

  for (const item of rawPlan) {
    if (!item || typeof item !== "object") continue;

    let { time, meal, caloriesEstimate } = item;

    if (typeof time !== "string" || typeof meal !== "string") {
      continue;
    }

    time = time.slice(0, 100);
    meal = meal.slice(0, 300);

    const cleaned = { time, meal };

    if (
      typeof caloriesEstimate === "number" &&
      caloriesEstimate > 0 &&
      caloriesEstimate < 5000
    ) {
      cleaned.caloriesEstimate = caloriesEstimate;
    }

    plan.push(cleaned);
  }

  if (plan.length === 0) {
    return { plan: [] };
  }

  if (plan.length > 40) {
    plan.length = 40;
  }

  return { plan };
}

// Tool schema（比 LM Studio / model 睇）
// 有三個 tools：getCurrentTime + createWorkoutPlan + createDietPlan
const tools = [
  {
    type: "function",
    function: {
      name: "getCurrentTime",
      description: "Get the current local time of the server.",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "createWorkoutPlan",
      description:
        "Create a full workout schedule. The model must generate the complete plan inside the 'plan' array before calling this tool.",
      parameters: {
        type: "object",
        properties: {
          plan: {
            type: "array",
            description:
              "The full workout schedule generated by the model. Each item represents one step in the schedule.",
            items: {
              type: "object",
              properties: {
                time: {
                  type: "string",
                  description:
                    "Time label, e.g. '8:00 AM' or 'Day 1 - Morning'.",
                },
                activity: {
                  type: "string",
                  description: "Workout description or instructions.",
                },
                durationMinutes: {
                  type: "integer",
                  description:
                    "Optional estimated duration in minutes for this activity.",
                },
              },
              required: ["time", "activity"],
              additionalProperties: false,
            },
          },
        },
        required: ["plan"],
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "createDietPlan",
      description:
        "Create a full diet / meal plan. The model must generate the complete plan inside the 'plan' array before calling this tool.",
      parameters: {
        type: "object",
        properties: {
          plan: {
            type: "array",
            description:
              "The full diet plan generated by the model. Each item represents one eating occasion.",
            items: {
              type: "object",
              properties: {
                time: {
                  type: "string",
                  description:
                    "Time label, e.g. '7:00 AM - Breakfast' or 'Lunch'.",
                },
                meal: {
                  type: "string",
                  description:
                    "Meal description, e.g. 'Oatmeal with berries and nuts'.",
                },
                caloriesEstimate: {
                  type: "integer",
                  description:
                    "Optional rough calorie estimate for this meal (in kcal).",
                },
              },
              required: ["time", "meal"],
              additionalProperties: false,
            },
          },
        },
        required: ["plan"],
        additionalProperties: false,
      },
    },
  },
];

// ---------------- Chat endpoint ----------------

app.post("/api/chat", async (req, res) => {
  try {
    const userMessage = req.body.message || "";
    const roomName = req.body.roomName || "General Health";
    const history = Array.isArray(req.body.history) ? req.body.history : [];

    const baseMessages = [
      {
        role: "system",
        content:
          "You are a friendly Cantonese-speaking health assistant. " +
          "Reply mainly in Cantonese, but keep health/fitness and nutrition terms in English when appropriate. " +
          "You MUST always remind users that you are not a doctor or dietitian. " +
          "If the user asks for a workout schedule, YOU MUST generate the full plan in the 'plan' array, then call createWorkoutPlan. " +
          "If the user asks for a diet plan, YOU MUST generate the full plan in the 'plan' array, then call createDietPlan. " +
          "Include all user constraints when generating the plan. " +
          "You MUST understand and use the conversation history to improve responses. " +
          `The current chat room name is: "${roomName}".`
      },

      // 🧠 加入 chatroom 過去 N 句歷史對話
      ...history,

      // 最新 user 呢句放最後
      { role: "user", content: userMessage },
    ];


    // 1️⃣ 第一次 call LM Studio：等佢決定用唔用 tools
    const first = await client.chat.completions.create({
      model: "nousresearch-hermes-2-pro-llama-3-8b-molecule16-i1",
      messages: baseMessages,
      tools,
      tool_choice: "auto",
    });

    console.log(
      "First response from LM Studio:",
      JSON.stringify(first, null, 2),
    );

    if (!first.choices || first.choices.length === 0) {
      return res.status(500).json({
        type: "text",
        message: "對唔住，AI 冇正常回應。",
        scheduleData: null,
        dietData: null,
        usedTool: false,
        raw: first,
      });
    }

    const firstMsg = first.choices[0].message;
    const toolCalls = firstMsg.tool_calls;

    // 如果冇用任何 tool → 普通文字回答
    if (!toolCalls || toolCalls.length === 0) {
      return res.json({
        type: "text",
        message: firstMsg.content,
        scheduleData: null,
        dietData: null,
        usedTool: false,
      });
    }

    // 情況 B：用咗 tools，我哋逐個執行，收集 scheduleData / dietData 俾前端畫卡
    const toolMessages = [];
    let scheduleData = null;
    let dietData = null;

    for (const call of toolCalls) {
      const toolName = call.function.name;
      let toolResult = null;

      // 將 arguments 由 JSON string 變成 JS object
      let args = {};
      try {
        args = call.function.arguments
          ? JSON.parse(call.function.arguments)
          : {};
      } catch (e) {
        console.warn("Failed to parse tool arguments:", e);
      }

      if (toolName === "getCurrentTime") {
        toolResult = getCurrentTime();
      } else if (toolName === "createWorkoutPlan") {
        const { plan } = createWorkoutPlanTool(args);
        toolResult = { plan };
        scheduleData = plan;
      } else if (toolName === "createDietPlan") {
        const { plan } = createDietPlanTool(args);
        toolResult = { plan };
        dietData = plan;
      } else {
        toolResult = { error: `Unknown tool: ${toolName}` };
      }

      toolMessages.push({
        role: "tool",
        tool_call_id: call.id,
        name: toolName,
        content: JSON.stringify(toolResult),
      });
    }

    // 2️⃣ 第二次 call LM Studio：畀 tool 結果，叫佢用自然語言講返
    const second = await client.chat.completions.create({
      model: "nousresearch-hermes-2-pro-llama-3-8b-molecule16-i1",
      messages: [...baseMessages, firstMsg, ...toolMessages],
    });

    console.log(
      "Second response from LM Studio:",
      JSON.stringify(second, null, 2),
    );

    if (!second.choices || second.choices.length === 0) {
      return res.status(500).json({
        type: "text",
        message: "對唔住，AI 喺處理工具結果時出現咗問題。",
        scheduleData,
        dietData,
        usedTool: true,
        raw: second,
      });
    }

    const finalMsg = second.choices[0].message;

    // 如果有 dietData → 優先當 diet card；
    // 其次如果有 scheduleData → 當 workout card；
    // 否則當普通 text
    let responseType = "text";
    if (dietData && dietData.length > 0) {
      responseType = "diet";
    } else if (scheduleData && scheduleData.length > 0) {
      responseType = "schedule";
    }

    res.json({
      type: responseType,        // "diet" / "schedule" / "text"
      message: finalMsg.content, // AI 用自然語言講返 result
      scheduleData: scheduleData,
      dietData: dietData,
      usedTool: true,
    });
  } catch (err) {
    console.error("Error in /api/chat:", err);
    res.status(500).json({
      type: "text",
      message: "Server error，請稍後再試。",
      scheduleData: null,
      dietData: null,
      usedTool: false,
      detail: String(err),
    });
  }
});

// 啟動 server
app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
